### ISSUE TITLE
Cannot talk to Vlad in NG+ after skipping the story & progressing past the initial dialog.

### ISSUE THREAD

**Issue by Dark-Thoughts** [Starfield-Community-Patch/Starfield-Community-Patch#1098]
Wasn't sure if this goes into NPCs or Missions & Dialogue.
There's just no dialog opening at all, the E button highlight just flashes briefly but he does not react at all to you. This is particularly frustrating if you happen to have survey data to sell.

### Details

NPC RefID: 002b0802

### Game Version

1.12.36

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Go through the Unity, skip the story, talk to Vlad to get the artifact locations, maybe re-enter the eye (haven't tried talking to him right after), fail to be able to enter a dialog with him.

**Comment by Deebz96** [comment]
I would have agreed that this was an oversight before, but looking at the conditions for his dialogue (including selling survey data), this is actually 100% intentional. Bethesda explicitly disabled this dialogue if you have skipped the main quest.

Since this crosses over into the territory of changing a design decision instead of fixing a bug, I'll mark this one as out-of-scope.
