### ISSUE TITLE
Game crashes when trying to land or go to Jemison Spaceport

### ISSUE THREAD

**Issue by ar1mperez** [Starfield-Community-Patch/Starfield-Community-Patch#1107]
Crash when trying to go to New Atlantis Spaceport

### Details

I installed the new update with the vehicle last night. Since then I completed the mission where you have to get the credentials on that cruise for Gal Bank (Crimson Fleet mission). 

After that, I tried to land at the starport in new atlantis, and my game crashed. I can fast travel to other parts of the city, but if I go too close to the starport section of the map, my game crashes.

### Game Version

11.13.61

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

I just go to New Atlantis and try to land or fast travel at the space port, and I crash

**Comment by Constellation-VASCO** [comment]
+1, same issue here!

**Comment by Deebz96** [comment]
The vast majority of people using this mod do not crash in New Atlantis, so I would sooner think this is a conflict with another mod in your load order, or that you are exceeding the master handle limit (otherwise known as the mod index limit, soft limit, etc).

Unless there are more specific reproduction steps that can be verified.

**Comment by Constellation-VASCO** [comment]
Hey, same issue here. I retturn to the game today with the last update and I crash every time I try to get to the spaceport (tram or telepotation). The topic is tag as "closed", did you find the way to fix this ? Thank you a lot
