### ISSUE TITLE
Orion Damage when adding weapon mods

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1124]
noticed a -80 dmg debuff on all Orion weapon mods except from standard/pre attached mods if the community patch is on the load order

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
install the community patch

**Comment by Deebz96** [comment]
This is almost certainly a menu display issue. Not an actual debuff. I’ve seen the menu claim some very wrong numbers, with no rhyme or reason.

It’s a bug with the vanilla game, not the SFCP. Are you able to provide any additional information, or screenshots?

**Comment by Deebz96** [comment]
Unable to replicate on my end. Since the SFCP does not touch the Orion, or any of its modifications, so I do not see how it would be causing this issue. Marking this one down as either a UI display bug, or something on the user's end.
![image](https://github.com/user-attachments/assets/29a28f2b-e971-4c36-a256-104716fef0eb)
