### ISSUE TITLE
Enemy ships in Vanguard Simulator are invisible.

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1132]
With SFCP enabled, the enemy ships in the Vanguard piloting Simulator are invisible and cannot be targeted.
Disabling the mod causes the ships to appear and be targeted.
Re-Enabling the mod causes the the ships to be invisible and cannot be targeted.

While invisible, the ships' location markers can be seen.

---

## Details 
Quest "Supra et Ultra" Vanguard piloting situation while in the simulator ship.

SFCP version 0.1.7, game version  1.13.61

## Game Version
1.13.61

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
1. Start Supra Et Ultra
2. Progress to the piloting simulation exam
3. Enter the simulator cockpit
4. Sit down in the pilot chair
5. Wait for enemy ship indicator to spawn
6. Manoeuvre the ship to make the indicator visible from the cockpit
7. The ship associated with the indicator is invisible and cannot be targeted

**Comment by Deebz96** [comment]
The SFCP is not causing this issue. You have another bug on your side. Ensure that the SFCP is at the top of your load order. May also need to disable other mods until you find the culprit. You may also be over the master handle limit, and need to remove some mods.
![image](https://github.com/user-attachments/assets/4c5235dc-6376-4fce-920d-8e593a3c3c94)

**Comment by Constellation-VASCO** [comment]
I don't know if I believe that. This is a new NG save so should not be near the master handle limit. 
→ Can you share a procedure for checking this limit?

There are no other ship-editing mods installed, as well as only 34 mods installed with no clothing or armor or outpost building mods which would add large numbers of Form IDs. 
This and two other bugs I hadn't yet separately reported exist only when Community Patch is enabled. 
One is also space-related, crashing when saving entering a space station.

So there may be some other sort of conditions at play which are not encountered in your current testing regimen.

**Comment by Constellation-VASCO** [comment]
Community Patch is the first in the load order below the Creations, whose load order cannot be controlled.
These creations are: Constellation.esm, sfbgs00a_a.esm sfbgs021.esm sfbgs023.esm sfta01.esm starfieldcompendium.esm SFBGS004.esm

**Comment by Deebz96** [comment]
As I mentioned previously, try disabling other mods until you find the culprit. If you cannot replicate the issue when only the SFCP is active in your load order, then you have another issue at play. If you find that you can disable any random set of mods to fix these issues, that means that your current load order is over the master handle limit.

**Comment by Constellation-VASCO** [comment]
Is there a procedure for checking the master handle limit?

**Comment by Constellation-VASCO** [comment]
With only Creations and Community Patch, the problem persists.

**Comment by Deebz96** [comment]
The master handle limit can be checked with an SFSE mod called Engine Fixes, on Nexus. Details are on the mod page.

You should disable the creations as well, and retest. Might want do a clean reinstall of the game too. The SFCP alone will simply not cause this issue in a game that is working correctly. It does not contain anything which could do so. People have named several mods as the cause of this issue, and of similar ones, since the last update. Without fail though, it is always an issue on the user’s end of some sort.

**Comment by Constellation-VASCO** [comment]
I have the Engine Fixes mod. The Description page and searching the Comments page show no entries for the phrase "handle"; is there another term I should be searching for to find the handle limit check?

**Comment by Deebz96** [comment]
I believe he calls it the mod index limit. The true term is master handle limit, however.

**Comment by Deebz96** [comment]
You know, I just had a thought. There is one thing we can test. Currently, the SFCP does not have the ship blueprints esm file listed as a master dependency. This isn’t needed, but with how broken the game’s mod support currently is, I’m wondering if this is somehow rarely leading to starfield.esm loading after the blueprints esm. That could very well cause invisible ships, since the starfield.esm version of ship records lack packin references.

Download 0.1.6 of the SFCP from the Nexus link below, and run that version temporarily. It had the blueprints esm as a master dependency. Don’t keep playing on your save after loading with the older version (just to be safe), but check to see if ships are suddenly visible with it. We might need to re-add that unnecessary master dependency to work around an engine bug for the time being.

https://www.nexusmods.com/starfield/mods/1?tab=files&jump_to_comment=143858874
