### ISSUE TITLE
Constellation characters crowd library after MQ

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1147]
After you get the last artifact, and One Giant Leap starts, you will see Vladimir, Barrett, Sam, Andreja, and Cora all sandboxing within the Lodge's library. This makes some sense at this stage, as everyone is waiting in anticipation of your return from the Buried Temple. If you jump to the Unity and return though, they will all still be crowding the library for the rest of that playthrough.

---

## Details 
This is because MQ305_SandboxAtLodgePkg [PACK:001F0B88] is given to these characters while this quest is running. However, aside from excluding active companions and crew, there are no other conditions for this package to ever end. Strictly speaking, this is working as designed, but it doesn't make sense for them to all remain in the library for the rest of time.

## Game Version
1.13.61.0

## New Game
Yes

## Reproduction Steps
Complete the main quest, go to the Lodge's library. Some of your companions, and Vlad, will be there indefinitely after this point.

**Comment by Deebz96** [comment]
I have added a couple of conditions to allow this package to end after certain points. The first one covers all characters except Vladimir, and will simply end the package when MQ305 reaches stage 100 [Player is in the Unity]. When you return to the Lodge, you'll find that everyone you left behind is now sandboxing normally, rather than crowding the display table.

Vladimir is handled differently by a new condition form, which will make him keep this package until you talk to him after returning from the Unity, OR indefinitely if Sarah "drew the short straw" during High Price to Pay.

The reasoning behind this is that he would become the new chair of Constellation after this point in the game, since half of the members are expected to leave this universe behind. So if plans change, and Sarah is still around to keep her role after the end of the MQ, Vlad will go back to The Eye. If she isn't, then he'll remain at the Lodge as a symbol of his new role.

[SFCP_1147.zip](https://github.com/user-attachments/files/16922866/SFCP_1147.zip)
