### ISSUE TITLE
[New Issue] Madame Sauvage's Place's Icon is labeled as Sleepcrate

### ISSUE THREAD

**Issue by gir489returns** [Starfield-Community-Patch/Starfield-Community-Patch#1152]
When using your scanner in Neon near Ebbside, you will notice that Madame Sauvage's Place's icon will show a martini glass, but is labeled as Sleepcrate. Clearly this is a copypaste error from Bethesda.

### Details

![image](https://github.com/user-attachments/assets/55188578-c995-431e-b863-be798a10d3c8)
![image](https://github.com/user-attachments/assets/d83468b4-74c5-4d27-b767-1a98f6a6a0fa)

### Game Version

1.13.61.0

### Language

English (EN)

### Have you recreated this issue on a new game?

Yes, I can recreate this issue.

### Reproduction Steps

Go to Ebbside.
Engage scanner.

**Comment by gir489returns** [comment]
I have found the offending form.

SFBGS008.esm:000078 CityMapMarkers_MadamSauavage

![image](https://github.com/user-attachments/assets/87388383-aded-476a-ba6b-20962eee2f6d)

**Comment by Deebz96** [comment]
I'll forward this one to BGS directly. Really appreciate the precise details on exactly where the issue is.

A fix via the SFCP is possible, but in my judgement, this is too small of an issue to be worth the complexity. Would need to deal with translations, and the fact that it's in SFBGS008 (very annoying with currently available tools). Better to just have this one addressed officially.

**Comment by Deebz96** [comment]
Turns out this should be fixed in the next update, just wasn't mentioned in the patch notes.

**Comment by gir489returns** [comment]
> Turns out this should be fixed in the next update, just wasn't mentioned in the patch notes.

Bethesda moment.
