### ISSUE TITLE
Concealment overrides Va'ruun magazines (again)

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1171]
This is not yet fixed in the base game and was un-fixed in sfcp 0.1.7 for some reason.

---

## Details 
Fix is present in sfcp 0.1.6.

## Game Version
Current non-beta

## New Game
Yes

## Reproduction Steps
Apply melee sneak attacks with va'ruun magazine perks and with/without concealment.

**Comment by Deebz96** [comment]
My mistake on that one, I think I see why. Are you willing to re-test it with this ESM?

[SFCP_1171.zip](https://github.com/user-attachments/files/17139045/SFCP_1171.zip)

**Comment by Constellation-VASCO** [comment]
Tested and can confirm that that ESM fixes the issue.

**Comment by Deebz96** [comment]
The actual fix that will be included in the next release will differ from the one uploaded above. That version worked by keeping the vanilla method of setting the sneak attack value, but changing the priority of the effect so that it no longer overrides other vanilla buffs/debuffs. This is how it worked in previous versions of the SFCP.

Now, it will work by multiplying sneak attack damage instead of setting it. The final math results are still the same, but this method makes the perk priority-agnostic with other buffs/debuffs. This is a better solution moving forward.
