### ISSUE TITLE
Sustenance feature not working in variant universe

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1175]
Sustenance feature not working during Revelation(MQ302b) quest in variant universes.

---

## Details 
In version 1.13.61.0, Bethesda officially revealed that it fixed this bug. However, Sustenance feature won't work during the Revelation(MQ302b) quest. Once you finish the quest, it will work again.

## Game Version
1.13.61.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Go to unity - enter the variant universe - collect artifacts - receive 'Revelation' quest

**Comment by Deebz96** [comment]
Checked this myself just now; turns out the issue is actually worse than that. After you collect the artifacts, Sustenance simply will not work again in that universe. Bethesda's fix only works while Among The Stars is running... so after it's completed, there's nothing left to make it work. I honestly don't know how they managed to do that lol

Bethesda's condition: Subject.GetQuestRunning(MQ402 [QUST:001DC418]) = 1
Our replacement condition: Subject.GetStageDone(MQ101 [QUST:00003448], 9000 Run on Stop) = 1

Fix attached:
[SFCP_1175.zip](https://github.com/user-attachments/files/17179450/SFCP_1175.zip)
