### ISSUE TITLE
Multiple quests bugged

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#1204]
* For "Kindness of Strangers", the objective, "pick up patient in Med Bay" takes me to the restaurant in The Well, and there's no one at the Med Bay for me to pick up.

* For "Hunted Homesteaders", I have an objective, "Talk to Group Leader" that either sends me to my ship cockpit or to a random spot on Nesoi about 900 meters away from the Player Home.

* Activity "Locate ECS Constant" ECS Constant is stuck orbiting Porrima II and no dialogue options complete the activity

---

## Game Version
1.8.86.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
For "Kindness of Strangers", Tahir is tied to both this quest and "Tale of Two Cities", which can cause either quest to block the other from being completed.

I don't know what is the cause for the other two quests.

**Comment by Deebz96** [comment]
1. Please keep individual issues to separate tickets.
2. These reports do not contain enough details for us to investigate.

Some notes:
- Kindness of Strangers is a prerequisite for Tale of Two Cities. It must be completed before the second quest will begin. This quest worked correctly for me recently, unable to troubleshoot without further reproduction steps.
- "Hunted Homesteaders" is a radiant quest. Not easy to troubleshoot, and issues may be random and/or caused by other mods. Issue is also already opened for it. #1080
- ECS Constant issues have been reported many times, and are well known. Issue for it is #431

**Comment by Constellation-VASCO** [comment]
Okay, the last two points are known issues, so that's good to hear.

However, (and a correction on my part), my mission list has "Two Tales, Two Cities" listed as completed.

Kindness of Strangers is still in my active mission tab (with Tahir unable to be found in the Med Bay.)

**Comment by Deebz96** [comment]
Then you managed to do those quests out of order somehow. That is likely the reason.
