### ISSUE TITLE
Delivering Devils Completion Glitch

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#129]
After completing the mission Delivering Devils Hadrian will stay in the closet of the bar on cydonia forever and you cant interact with her at all the game also does not give you the subsequent mission eyewitness

---

## Details 
i am un sure of these not a very technical person

## Game Version
Steam Build ID 12051365

## New Game
Yes

## Reproduction Steps
I just did the quest again and it happened again not sure its working as intended at least on my pc

**Comment by Constellation-VASCO** [comment]
After having this bug plague me for the entire playthrough, I figured out why it happens. The female ship technician at the spaceport (RefID 00252349) is erroneously marked as a required alias on the UC04 quest, despite serving no role in it. If she ends up dying for whatever reason, the quest will always fail to start. I made a retroactive fix to make the ship technician alias optional, as well as 2 more aliases which serve a very minor role, but are marked as required for the quest: https://www.nexusmods.com/starfield/mods/7190/.

**Comment by DJLegends1011** [comment]
> After having this bug plague me for the entire playthrough, I figured out why it happens. The female ship technician at the spaceport (RefID 00252349) is erroneously marked as a required alias on the UC04 quest, despite serving no role in it. If she ends up dying for whatever reason, the quest will always fail to start. I made a retroactive fix to make the ship technician alias optional, as well as 2 more aliases which serve a very minor role, but are marked as required for the quest: https://www.nexusmods.com/starfield/mods/7190/.

thank you for the mod was sadly the lucky ones that got this bug

**Comment by Aurelianis** [comment]
For the following aliases:
ShipTech02
MinisterHallGuard
MASTFemaleWorker03

I've set the following flags. I chose these flags as they are more in line with what Beth does with non-essential generic NPC aliases.
Allow Reuse In Quest
Allow Dead
Allow Disabled
Allow Reserved
Allow Destroyed

I've also had issues with the quest starting and in order to test I made pretty much all aliases optional to determine which aliases were not being filled. In my case ChiefYasin's alias was not filled but he can't be optional so instead I flagged him as Allow Disabled and that worked. So I've added the Allow Disabled to the following aliases:
PresidentAbello
AdmiralLogan
ChiefSarkin
ChiefPatel (this is Kulkarni)
ChiefYasin

Fix: 
[SFCP_Issue_129.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15393505/SFCP_Issue_129.zip)

**Comment by Constellation-VASCO** [comment]
The RunInGuards alias is also a breaking point and iirc they're already marked as allow dead, disabled and deleted, check the mod posted above for more details.

Please consider reevaluating this solution, as I'm not convinced that it is reliable or comprehensive enough, instead of marking the aliases as optional altogether.
