### ISSUE TITLE
Family Reunion Quest not starting

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#157]
The family reunion quest with Abe doesn't start 

---

## Details 
The quest for family reunion the Constant doesn't start after speaking to Abe when the Grav Drive is installed. It repeats it as an activity to speak to him but you never get the letters from him and start the quest. 

## Game Version
Latest Version

## New Game
Yes

## Reproduction Steps
Install the grav drive and speak to Abe on the constant

**Comment by ja231c** [comment]
This bug also happens if you let them stay at Paradiso.
For reference, the quests in question are:

1. FFConstantR02Misc "Misc Pointer" [QUST:00211126]
2. FFConstantR02 "Family Reunion" [QUST:00211125]

The FFConstantR02 should start if players agrees to help Abe in FFConstantR02Misc at stage 1000 but for some reason this never happens, no idea why.

**Comment by ja231c** [comment]
It appears that the game completely refuses to start FFConstantR02, I tried to start it with console commands (both via sending the FFConstantR02QuestStartKeyword [KYWD:0021108B] (like the script for starting this quest does) via CreateEvent and via StartQuest - it does not start.

**Comment by ja231c** [comment]
I made an ESM with all the aliases set to Optional; FamilyLoc, FamilyMarker, Family did not get filled

Family seems to require FamilyMarker which in turn requires FamilyLoc which is supposed to be a location with LocTypeSettlement keyword that contains Location Cell Static Reference of type FFConstantR02_CitizenMarker_LocRef [LCRT:0021108C]

alright, I think I've figured it out! the game for some reason thinks that all locations that would be valid for this quest are "cleared", since this alias cannot be filled with cleared locations it does not get filled

I'd wager the same thing is causing #471 

adding "Allow Cleared" to the "FamilyLoc" alias makes the FFConstantR02 quest work but this
this however is not a good solution, the proper solution would to figure out why those locations are marked as cleared

**Comment by Constellation-VASCO** [comment]
What makes you think ignoring cleared locations is the wrong approach? I think it might be an error that the alias is even checking for that.

**Comment by ArkangelCorvus** [comment]
Family Reunion has been exclusively sending me to the Red Mile (ironically in the same system as the Constant's original location. I haven't completed the Red Mile quest on this run. If I'm reading the comments correctly, this is the same bug?

**Comment by ja231c** [comment]
Yes, this would be the same bug.

**Comment by gir489returns** [comment]
This bug is still present in 1.10.32.

**Comment by Constellation-VASCO** [comment]
Still bugged as of today

**Comment by gir489returns** [comment]
This is still bugged.

**Comment by Constellation-VASCO** [comment]
isLazy's fix for this has been working just fine. It's a minimally invasive fix that wouldn't cause any issues even if Bethesda changes how settlements can be marked cleared. IMHO including it is a no-brainer. See https://www.nexusmods.com/starfield/mods/8361 

It's just conjecture that settlements being marked as cleared is a mistake anyway. We don't *know* that, and changing it could cause issues (i.e. in future quests/DLC) if it *is* intended. Go with the simple, proven fix that won't cause issues elsewhere.

**Comment by Deebz96** [comment]
[SFCP_157.zip](https://github.com/user-attachments/files/16900397/SFCP_157.zip)

**Comment by gir489returns** [comment]
> isLazy's fix for this has been working just fine. It's a minimally invasive fix that wouldn't cause any issues even if Bethesda changes how settlements can be marked cleared. IMHO including it is a no-brainer. See https://www.nexusmods.com/starfield/mods/8361

All he's doing is setting the Allow Cleared flag, like @ja231c speculated was the problem.
