### ISSUE TITLE
Content short circuit CI step false positives

### ISSUE THREAD

**Issue by Noggog** [Starfield-Community-Patch/Starfield-Community-Patch#261]
I added this commit 903068c7e4fad8dc823c30e6f20ed82ee3f4931a
And the following night it was seen as content to publish 
https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/actions/runs/6282804887

This suggests the logic isn't working as intended, as it should only republish if `src/plugins` was modified (at least in its current code)

**Comment by Noggog** [comment]
Feels like the `--since="1 days ago"` isn't quite doing its job:

Run on 9/23/2023:
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/24981326/6f14e5dd-9628-4aec-99ad-f1502473f2e8)

Returning entries for Sep 19th?

**Comment by FlayaN** [comment]
@Noggog 
(I run these in git-bash locally so I get use grep as well FYI)

Can you try to run this locally using the latest git

`git --version`
>git version 2.42.0.windows.2

`git log --since="2 days ago" --name-only --oneline --follow src`
>acd8d86 Added a placeholder readme in the external files
src/loose/Docs/Readme.txt

`git log --since="15 days ago" --name-only --oneline --follow src`

>acd8d86 Added a placeholder readme in the external files
src/loose/Docs/Readme.txt
ef2ef97 Moved spriggit plugin data to /plugin subfolder
src/plugin/RecordData.yaml
b56b38c Update RecordData.yaml
src/RecordData.yaml
94c148c Baseline mod header utilizing Spriggit
src/RecordData.yaml


If that works we can check if the number of rows returned for that command (with 1 days ago still) is 0 or not

`git log --since="1 days ago" --name-only --oneline --follow src | grep . -c`

This returns how many rows the previous command contains, so if that is 0 then we should not run the next job

**Comment by Noggog** [comment]
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/24981326/484ae3ee-421b-4d12-8afe-c491a1c31c91)

Seems like we match
