### ISSUE TITLE
"Pierogi" food is called "Pierogis"

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#28]
The food item should be called "Pierogi" since "Pierogi" is already plural, singular is "Pieróg".

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Find pierogi, observe that it is erronously called "pierogis"

**Comment by Constellation-VASCO** [comment]
Actually, this is only the case in Polish.  When English "borrowed" this word, it ditched the original derivative forms of it.  Even Merriam-Webster lists "Pierogis" as being right.  Some people even spell it "Pierogies."  I think this one is probably a matter of taste, but almost nobody in English would ever say "Pieróg" unless they also spoke and were familiar with Polish.

**Comment by Constellation-VASCO** [comment]
Merriam-Webster does not list "Pierogis" as correct, I checked, it lists "Pierogi", "Pierogies" and "Pirogi", it has no entry for "Pierogis".

**Comment by ja231c** [comment]
Some more detail:
1. The item in question is Food_Served_Tavern_Pierogis "Pierogis" [ALCH:00249C13], they even misspelled the Editor ID!
2. The Food_Served_CanUck_Edmontonian "CAN-uck! Edmontonian" [ALCH:00249C4A] item contains "Pierogies" in the description, which while at least technically correct according to Merriam-Webster... changing it to "Pierogi" would be prefferable as that is even more correct, but I won't complain too much if only that atrocious "Pierogis" gets changed to "Pierogies" (for consistency) in order to avoid modifying an extra record; That being said - the preffered solution would be to change both instances to "Pierogi".

**Comment by Constellation-VASCO** [comment]
CAN-uck items should use Canadian English due to the obvious national connection of this brand. In Canadian English the most common plural spelling is "perogies" , with "pierogies" and "pierogi" about equally common but even added together they're less common that "perogies". Leading national brands like No Name and Cheemo use "perogies". "Pierogis" is not a common spelling and I agree with @ja231c that it should not be used, but IMO "perogies" is the preferable spelling for this item. [Google Trends supports this:](https://trends.google.com/trends/explore?date=today%205-y&geo=CA&q=Pierogis,Pierogi,Perogies,Pierogies&hl=en).

**Comment by Constellation-VASCO** [comment]
Based on Sovetskysoyuz's comment, I don't think we'll be applying this change. Feel free to make a patch with this change in it as a separate mod!
