### ISSUE TITLE
Styx can't get clean!

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#32]
The graffiti on Styx should be gone... it isn't.

---

## Details 
The graffiti on Styx is intended to be cleaned after the Bare Metal quest, and dialog with both Styx and Renick indicates it has been.

![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/36433/3d541e9b-4446-4a0b-bdf3-0961fd9cfd51)

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
Complete the Bare Metal quest on Neon.

**Comment by Bobbyclue** [comment]
From what I can tell there is handling to clean Styx up in the game. It seems to be intended to fire after completing this quest, leaving Neon, and returning to Neon. There's a script on the quest that should run upon returning at stage 100, which is when the quest is visibly completed for the player. The quest is not shut off at this point. 

At a guess I'd say that the dialogue either is conditioned on stage 100 rather than 200 (which is when Styx is clean), or the remove/attachmod functions bethesda used to clean him up are not enough and there's another thing keeping the visible graffiti on Styx.

Either way more advanced tools will be needed for a proper fix.

**Comment by Pickysaurus** [comment]
[FFNeonZ03Fix.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13071524/FFNeonZ03Fix.zip)
This ESM assigns a dialogue condition (but it may not be needed)

**Comment by Constellation-VASCO** [comment]
I've made a new ESM that swaps his skin back to default but the OMOD doesn't seem to apply over the top of it properly.

**Comment by Constellation-VASCO** [comment]
Seems to be using textures under `textures\actors\modela\modela_combat_01\graffitistyx` for the base skin. 

This doesn't seem to be something that can be solved without use of the Creation Kit

**Comment by Constellation-VASCO** [comment]
With the latest release of xEdit, additional research and testing can be done. There are multiple ways of applying the skin overlay that may be explorable.

000A920E - bot_ModelA_Styx_Graffiti_01
0001671C - bot_ModelA_Civ_01

**Comment by Constellation-VASCO** [comment]
Aha, I got it to work with a layered material swap, it just requires leaving the cell Styx is in and going back, then the graffiti is gone

This changes Styx to have `Skin_ModelA_Combat_Generic_Heavy "SkinModelA Generic HeavyCombat" [ARMO:00319B37]` instead of the graffiti armour as his Skin and changes `bot_ModelA_Styx_Graffiti_01 [OMOD:000A920E]` to have a NPC - Layered Material Swap property with `LMS_ModelA_Combat_Graffiti [LMSW:000B41CA]`
You can test the quest by running the following commands or playing through Styx's quest normally
```
startquest a935f
setstage a935f 200
```
