### ISSUE TITLE
Into the unknown quest bug

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#42]
Quest does not appear of quest log, unable to advance the main quest as a result. The Reddit IRL attached to this report goes into further detail with multiple parties across PC and console having the same issue. 

---

## Details 
https://www.reddit.com/r/Starfield/comments/1684aht/main_quest_bug_into_the_unknown/

## Game Version
12053165

## New Game
Yes

## Reproduction Steps
From what I have read it has to do with advancing the Crimson Fleets missions before Constellation with then can cause the bug.

**Comment by MistaOmega** [comment]
Some more information as I've been digging into this one.

I too had an issue because I did crimson fleet quests first.

It doesn't allow the quest to start at all, it shows up as stopped by doing player.sqs 160a9

Sqs shows stage 0 and stopped

Advancing to any of the stages does not progress

Reset quest does nothing

Completequest removes the dialogue about Vlad from Sarah, nothing else

Progression can be forced by starting the next quest and being forced to Neon with Walter. This leaves Andrejas dialogue bugged.

Don't know if any of that's of use, but that's what I've found

**Comment by Constellation-VASCO** [comment]
I've had this issue too but the quest failed to appear before doing any Crimson Fleet stuff. My order of playing was I got the Constellation quest with Sarah, did the UC faction quest, after which the Deep Cover (start of the Crimson Fleet quest) quest became available but instead I did the Constellation quest with Sarah, then the Rangers quest and then the Constellation quest with Sam. Into The Unknown failed to appear. I didn't even know it was a bug initially and started doing some side quests and eventually started Deep Cover.

**Comment by juliocoliveira** [comment]
I had this issue, It seems to resolve itself randomly after a time.
No console commands work.
I saw on reddit that for everybody it happens to show randomly playing it normally.
One guy said that he waited for 3 days and it showed.

**Comment by juliocoliveira** [comment]
This seems to be fixed by Bethesda in the latest patch.
Cannot confirm that it was really fixing, because I'm not facing this bug anymore, before the patch was released.

**Comment by Aurelianis** [comment]
Closing as fixed by Bethesda.
