### ISSUE TITLE
Various skill fixes

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#433]
Various skills don't work as intended. 

---

## Details 
- Armor Penetration: Now works for melee weapons (excluding unarmed attacks.)
- Concealment: No longer overrides the magazine perks from Va'ruun scriptures or interferes with Void Form. Void Form, Concealment and Chameleon will seamlessly switch between their effects, with Void Form taking priority. (Note: Chameleon is probably not supposed to stack with itself, but the players love it. I can provide a fix if you want to risk the ire of the playerbase.)
- Lasers: No longer affects particle weapons. (Expect complaints.)
- Leadership: Fixed a bug that caused ranks 2-4 to only provide +15% companion affinity gain instead of +25%.
- Martial Arts: Now properly adds a flat +15% crit chance to unarmed attacks instead of multiplying your base 5% crit chance by 1.15. Ranks 3-4 also have a 15% chance to disarm as intended. (Was 5%)
- Particle Beams: Now properly adds a flat +5% crit chance, instead of multiplying your base 5% crit chance by 1.05.
- Pistol Certification: Now properly adds a flat +25% crit chance for 5 seconds after killing an enemy, instead of multiplying your base 5% crit chance by 1.25.
- Rapid Reloading: Now works while throwables are equipped.
- Rejuvenation: Fixed health regeneration in combat not working. Ranks 3 and 4 now allow you to regenerate health half as fast in combat, which is what the developers intended. (Overwrite the fix from v0.0.1, this fix is better.)
- Shield Systems: Can no longer increase shields beyond the intended amount. (The bug where it reduces shields is still present, see the sticky post on Skill Fixes for a comprehensive explanation.)
- Targeting: Fixed a bug that made the increased weapon range not take effect at rank 3 only.
- Targeting Control Systems: Now properly adds a flat +10% crit chance at rank 4
- Cellular Regeneration: Rank 4 now lists that it further increases the recovery chance.
- Decontamination: Rank 4 now lists that it further increases the recovery chance.
- Gunslinger's Guide and Mining Monthly magazine perks no longer count toward the skill total for the Combat tree. 
- Automated Weapon Systems, it appears to work for all weapons even though it's only supposed to work for turrets.

[SkillFixes_-_Community_Patch.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/13196142/SkillFixes_-_Community_Patch.zip)

## Game Version
1.7.36.0

## New Game
Yes

## Reproduction Steps
Check the skills

**Comment by Pickysaurus** [comment]
- [ ] Armor Penetration: Now works for melee weapons (excluding unarmed attacks.)
- [ ] Concealment: No longer overrides the magazine perks from Va'ruun scriptures or interferes with Void Form. Void Form, Concealment and Chameleon will seamlessly switch between their effects, with Void Form taking priority. (Note: Chameleon is probably not supposed to stack with itself, but the players love it. I can provide a fix if you want to risk the ire of the playerbase.)
- [ ] Lasers: No longer affects particle weapons. (Expect complaints.)
- [ ] Leadership: Fixed a bug that caused ranks 2-4 to only provide +15% companion affinity gain instead of +25%.
- [ ] Martial Arts: Now properly adds a flat +15% crit chance to unarmed attacks instead of multiplying your base 5% crit chance by 1.15. Ranks 3-4 also have a 15% chance to disarm as intended. (Was 5%)
- [ ] Particle Beams: Now properly adds a flat +5% crit chance, instead of multiplying your base 5% crit chance by 1.05.
- [ ] Pistol Certification: Now properly adds a flat +25% crit chance for 5 seconds after killing an enemy, instead of multiplying your base 5% crit chance by 1.25.
- [ ] Rapid Reloading: Now works while throwables are equipped.
- [ ] Rejuvenation: Fixed health regeneration in combat not working. Ranks 3 and 4 now allow you to regenerate health half as fast in combat, which is what the developers intended. (Overwrite the fix from v0.0.1, this fix is better.)
- [ ] Shield Systems: Can no longer increase shields beyond the intended amount. (The bug where it reduces shields is still present, see the sticky post on Skill Fixes for a comprehensive explanation.)
- [ ] Targeting: Fixed a bug that made the increased weapon range not take effect at rank 3 only.
- [ ] Targeting Control Systems: Now properly adds a flat +10% crit chance at rank 4
- [ ] Cellular Regeneration: Rank 4 now lists that it further increases the recovery chance.
- [ ] Decontamination: Rank 4 now lists that it further increases the recovery chance.
