### ISSUE TITLE
NPC dropping presumably unique and wrong items during quest "Rook meets King"

### ISSUE THREAD

**Issue by ChankaGH** [Starfield-Community-Patch/Starfield-Community-Patch#46]
**Details**
During the introductory mission to the Crimson Fleet the player is asked to track down and kill a former member. You board the ship and get the option to either convince or kill. If you choose to kill everyone on board of the ship, the captain Dimitri (FF034FFC) drops both the MK1 Spacesuit and the MK1 Boostpack. This suit is the same one thats locked behind a masterlock in the basement of the constellation lodge, which leads me to believe its supposed to be a unique item, and not supposed to drop from some random quest NPC.

**Game Version**
1.7.23.0

**New Game**
Yes

**Reproduction Steps**
Follow UC Questline until you are supposed to infiltrate Crimson Fleet. When you get the quest "Rook meets King", board the ship with Austin Rake on it, and after talking to the captain, kill everyone on board. Loot the captain. 
![image](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/assets/72355618/a1405d54-9547-449e-af9b-2e5441ab15e7)

**Comment by Aurelianis** [comment]
I've checked Dmitri's record and he is assigned a Settler Spacesuit and Captain's clothing. Went through the levelled lists and did not find any mention of the Mark I. This may have been fixed by Beth after this issue was reported. Closing as cannot reproduce/stale. If the issue does still persist with the latest version (v1.11.36.0 at the time of this post) or later, please reopen the issue.
