### ISSUE TITLE
Editing Ship Breaks Ship Door

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#78]
Adding or upgrading parts in the ship builder makes the door into and out of the ship and all future ships inaccessible. Can still enter to and from the cockpit. Companions also no longer appear inside the ship. It leads to many other things breaking such as not being able to actually swap out companions as they aren't in your ship despite the menu saying they are, as well as causing many problems when you aren't able to enter the ship from the menu. Issue persists on swapping ships. Not all ships cause it, for instance the UC Prisoner Transport had parts added just fine, but even just upgrading parts on the Frontier activates the glitch.

---

## Game Version
1.7.23.0

## New Game
No

## Reproduction Steps
I'm not sure if it persists on new games, however loading older saves and trying different ships still causes it. I know it has 100% happened with the Frontier while replacing the missile launcher with an EM cannon and while upgrading the grav drive to the next best model. It's a common enough glitch however. https://www.reddit.com/r/Starfield/comments/1692uyr/cant_access_my_own_ship_directly/

**Comment by MusaFuchs** [comment]
I've gathered a bit more info and identified further causes of this bug.

**Stealing Ships:**

Stealing ships is able to trigger this bug. On my secondary save I stole a ship, set it as home, and system-hopped around a couple times before two things happened:
1. On the scanner and the bay-hatch the ship is referred to as "Ecliptic Combat A01" instead of it's original name. In the ship/crew/modify/buy menus it reads as it's original name. 
2. The bay-hatch reads as "[Inaccessible]".

On my primary save I stole a ship, flew back to port to register the ship, and then modified, renamed, and saved the ship, prompting the [inaccessible] bay hatch to start. This cause a similar behavior with the exception that the name reads correctly on the scanner. At some point during the journey to try and fix this issue - the name on this ship ALSO reverted to "Ecliptic Combat 01. These two saves are on completely separate devices. 

[This reddit comment](https://old.reddit.com/r/Starfield/comments/16ibspe/attention_ship_ownership_bug_causing_many_issues/k22rv7r/?context=10000) provides more details on the issue, and reaffirms my guess that this is related to the game somehow pointing toward the wrong ship.

**Modifying:**
After 20+ hours of gameplay and dozens of uneventful modification sessions, my Frontier gained the [Inaccessible] bug. A reddit post suggested removing the "Dragon 221"s, this fixed the bay hatch being inaccessible but I STILL cannot get people assigned to my ship to show up on it. Vasco does not appear outside the ship on planets nor space-stations.

I have two save files I'm happy to upload if you need one. One has several hours but almost zero quest progress.

**Comment by Deebz96** [comment]
The ship builder system is a fairly buggy one that Bethesda has been tinkering with since launch. These of issues require engine-level fixes, which are out of scope of the SFCP.
