### ISSUE TITLE
The Den - COM Commentary

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#908]
Entering The Den, companions have a single line of commentary and they will repeat it with either a very short cool down or none at all

---

## Details 
Entering The Den, companions have a single line of commentary and they will repeat it with either a very short cool down or none at all, which is pretty annoying. Sarah seems to be the only one who has Say Once Response Flag over hers and works correctly. I added it to 1E9CD4, 23EEAF & 1C7130 in my Den mod, which worked out well.

## Game Version
1.9.71.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Description

**Comment by Aurelianis** [comment]
001E9CD4 is an INFO, but the other 2 are DIAL, so instead of adding Say Once on the DIAL (which would add it to all INFOs) 23EEAF & 1C7130, I specifically added it to the INFO for the Den, 0023EB98 & 001A4A3A, respectively. 

Fix: [SFCP_Issue_908.zip](https://github.com/Starfield-Community-Patch/Starfield-Community-Patch/files/15392525/SFCP_Issue_908.zip)
