### ISSUE TITLE
Disciples keep respawning after the quest

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#975]
The disciples in the Neon Side - Quest: The Showdown (City_Neon_Gang03) respawn consistently whenever I return to Neon. They tend to open fire from Ebbside as soon as I disembark from my ship or start walking in that area, leading to a chaotic scene where all the NPCs flee in panic and disappear.

---

## Details 
The quest that triggers them to spawn is: The Showdown (City_Neon_Gang03)
They continue to reappear even after the completion of the quest (at least 700 hours ago)

## Game Version
V1.11.36.0

## Language
English (EN)

## New Game
No

## Reproduction Steps
-

**Comment by Deebz96** [comment]
Confirmed. These NPCs are part of the Neon location, and are initially disabled. This quest enables them, but seems to never disable them after. They will respawn with a cell reset.

- 00214811
- 00214812
- 00214813
- 00214814
- 00214815
- 0021481B
- 0021481C
- 0021481D
- 00214817
- 00214818
- 00214819

**Comment by Deebz96** [comment]
As it turns out, all three Strikers quest have this issue with the Disciples never being disabled afterwards. The third quest, The Showdown, also does not shut down after exiting the warehouse. It instead only shuts down if you exit, and then re-enter.

Fix attached for the quest fragment scripts on all three quests, and a fix for the script property on The Showdown's QUST record, which prevents it from shutting down properly:
[SFCP_975.zip](https://github.com/user-attachments/files/16860293/SFCP_975.zip)


A retroactive fix is proving to be difficult, as these NPCs are no longer aliases of their original quests after they are ended. In order to successfully disable them retroactively, I'll need to re-acquire them as aliases in a hotfix quest, and disable them that way. This could come with its own potential issues though. Will need to investigate further.
