### ISSUE TITLE
Incorrect Display of Skill Magazines

### ISSUE THREAD

**Issue by Constellation-VASCO** [Starfield-Community-Patch/Starfield-Community-Patch#984]
The 'TrackersAlliancePreparednessPrime' series of Magazines always displays SkillMagazine number 4.

---

## Details 
The error is that the same nif file is always called up for all 5 magazines. But the nifs, materials and textures are present
These are the wrong formIDs:
00209097: MODL: Items\Magazines\TrackersAlliance_04.nif
must be: Items\Magazines\Magazine_TrackersAlliance_05.nif

00209099: MODL:
Items\Magazines\Magazine_TrackersAlliance_04.nif
must be:
Items\Magazines\Magazine_TrackersAlliance_03.nif

0020909a: MODL:
Items\Magazines\TrackersAlliance_04.nif
must be:
Items\Magazines\Magazine_TrackersAlliance_02.nif

0020909b: MODL:
Items\Magazines\TrackersAlliance_04.nif
must be:
Items\Magazines\Magazine_TrackersAlliance_01.nif

## Game Version
1.11.36.0

## Language
English (EN)

## New Game
Yes

## Reproduction Steps
Collect all TrackersAlliance Magazines and look that all are the same.

**Comment by Deebz96** [comment]
This appears to have been intentional. Models 01, 02, 03, and 05 all mention specific weapon types. 04 has a generic "Accelerated Combat Training" cover. When you match the the books with the models they were supposed to have, the perks given by these books don't match the cover anymore.

We could change the perks to match the covers, but that would cross the line of bug fixing.

Because of this, I will veto this one. Even though it stings to see four perfectly good models go to waste. This would be a good change for a separate mod though.
